name: CI

on: [push]

jobs:
  rspec:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      # Add or replace dependency steps here
    - name: Install Ruby and gems
      uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e # v1.92
      with:
        bundler-cache: true

    - name: Run tests
      run: |
        bundle exec rspec